name: Manual Docker Cleanup
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run mode'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Clean Docker Hub
        uses: lostlink/docker-cleanup@v1.0.1
        with:
          username: ${{ vars.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repositories: 'ish'
          dry-run: ${{ github.event.inputs.dry_run }}
          verbose: true
